services:
  localstack:

    image: localstack/localstack:0.11.2
    container_name: localstack_dllo
    ports:
      - '4563-4599:4563-4599'
      - '8055:8080'
    environment:
      - AWS_DEFAULT_REGION=us-east-2
      - SERVICES=s3,sns,sqs,dynamodb
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - EDGE_PORT=4566
      - PERSISTENCE=true
    volumes:
      - './data:/tmp/localstack/'
      - '/var/run/docker.sock:/var/run/docker.sock'